### ISSUE TITLE
询问linux内核关于a64芯片的支持，主要是gpio和视频解码

### ISSUE THREAD

**Issue by yxteagle** [linux-sunxi/libcedrus#1]

**Comment by jemk** [comment]
English please.
This isn't the right place to ask about kernel and gpio.
Video decoding should be possible on A64, maybe some small adjustments are necessary.

**Comment by yxteagle** [comment]
If possible. please provide available linux kernel of A64. 
If you have the source about kernel and driver of gpio and ve, or demo about gpio and hw decode.
It's very kind of you to give the links of source to me.
Thank you for answering.

**Comment by jemk** [comment]
http://wiki.pine64.org/index.php/Pine_A64_Software_Release#Linux_BSP_Related
http://forum.pine64.org
